os: linux
dist: focal
language:
  python
python:
  - "3.8"

before_install:
  - sudo apt-get install tcpdump
  - sudo apt-get install tshark
install:  
  - pip install coverage
  - pip install -r requirements.txt
script:
  - coverage run indoor_localizer.py --test
after_success:
  - bash <(curl -s https://codecov.io/bash)
